version: '2'
services:
    web:
        build: .
        ports:
            - "80:80"
            - "3000:3000"
            - "3001:3001"
            - "8080:8080"
        volumes:
            - .:/var/www/html
            - ./devops/apache2/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
        links:
            - db
    db:
        image: mysql
        ports:
            - "3307:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=financeial
            - MYSQL_USER=financeial
            - MYSQL_PASSWORD=123